### ISSUE TITLE
error-running-script

### ISSUE THREAD

**Issue by sebastienvg** [kajisaap/rocketchat-pagerduty#1]
Trying to use this script on our rocket.chat instance and the message come to rocket.chat empty. I tried to use the curl to see what's the error

curl -X POST -H 'Content-Type: application/json' --data '{"icon_emoji":":ghost:","text":"Example message","attachments":[{"title":"Rocket.Chat","title_link":"https://rocket.chat","text":"Rocket.Chat, the best open source chat","image_url":"https://rocket.chat/images/mockup.png","color":"#764FA5"}]}' https://my_rocket_chat_server/hooks/my_token

{"success":false,"error":"error-running-script"}

Anyone having the same issue, did I miss something?

**Comment by fninja** [comment]
getting the same issue.. no PD messages once i activate the script, empty messages when it's not activated.  
A snippet from the log:
```TypeError: Cannot read property 'incident' of undefined       at Script.process_incoming_request (script.js:1:268)       at evalmachine.<anonymous>:1:8       at ContextifyScript.Script.runInContext (vm.js:59:29)       at ContextifyScript.Script.runInNewContext (vm.js:65:15)       at Object.runInNewContext (vm.js:135:38)       at Object.executeIntegrationRest [as action] (meteor://💻app/packages/rocketchat_integrations.js:2389:25)       at Route.share.Route.Route._callEndpoint (meteor://💻app/packages/nimble_restivus.js:347:32)       at meteor://💻app/packages/nimble_restivus.js:236:33       at packages/simple_json-routes.js:98:9 ```

**Comment by fninja** [comment]
i added a merge request after inspecting an actual payload from pd using the awesome service on https://requestinspector.com

**Comment by kaji-bikash** [comment]
wow I am late.
